services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-syllabus}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio-data:/data

  clamav:
    image: mkodockx/docker-clamav:alpine
    platform: linux/arm64/v8
    command: clamd -F
    ports:
      - "3310:3310"

  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    env_file:
      - ../../.env
    environment:
      PYTHONPATH: /app
      POSTGRES_DSN: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-syllabus}
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_SECURE: "false"
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"
    command: ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.worker
    env_file:
      - ../../.env
    environment:
      PYTHONPATH: /app
      POSTGRES_DSN: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-syllabus}
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_SECURE: "false"
    depends_on:
      - postgres
      - redis
      - minio

  ui:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.ui
    environment:
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ../..:/app

volumes:
  pgdata:
  minio-data:


